// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/market.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Weapon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	WeaponType    string                 `protobuf:"bytes,3,opt,name=weapon_type,json=weaponType,proto3" json:"weapon_type,omitempty"`
	DamageMin     uint64                 `protobuf:"varint,4,opt,name=damage_min,json=damageMin,proto3" json:"damage_min,omitempty"`
	DamageMax     uint64                 `protobuf:"varint,5,opt,name=damage_max,json=damageMax,proto3" json:"damage_max,omitempty"`
	Weight        float64                `protobuf:"fixed64,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Price         uint64                 `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	Rarity        string                 `protobuf:"bytes,8,opt,name=rarity,proto3" json:"rarity,omitempty"`
	SpecialEffect string                 `protobuf:"bytes,9,opt,name=special_effect,json=specialEffect,proto3" json:"special_effect,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weapon) Reset() {
	*x = Weapon{}
	mi := &file_proto_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weapon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weapon) ProtoMessage() {}

func (x *Weapon) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weapon.ProtoReflect.Descriptor instead.
func (*Weapon) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{0}
}

func (x *Weapon) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Weapon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Weapon) GetWeaponType() string {
	if x != nil {
		return x.WeaponType
	}
	return ""
}

func (x *Weapon) GetDamageMin() uint64 {
	if x != nil {
		return x.DamageMin
	}
	return 0
}

func (x *Weapon) GetDamageMax() uint64 {
	if x != nil {
		return x.DamageMax
	}
	return 0
}

func (x *Weapon) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Weapon) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Weapon) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *Weapon) GetSpecialEffect() string {
	if x != nil {
		return x.SpecialEffect
	}
	return ""
}

func (x *Weapon) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Armor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ArmorType     string                 `protobuf:"bytes,3,opt,name=armor_type,json=armorType,proto3" json:"armor_type,omitempty"`
	Defense       uint64                 `protobuf:"varint,4,opt,name=defense,proto3" json:"defense,omitempty"`
	Weight        float64                `protobuf:"fixed64,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Price         uint64                 `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	Rarity        string                 `protobuf:"bytes,7,opt,name=rarity,proto3" json:"rarity,omitempty"`
	SpecialEffect string                 `protobuf:"bytes,8,opt,name=special_effect,json=specialEffect,proto3" json:"special_effect,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Armor) Reset() {
	*x = Armor{}
	mi := &file_proto_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Armor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Armor) ProtoMessage() {}

func (x *Armor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Armor.ProtoReflect.Descriptor instead.
func (*Armor) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{1}
}

func (x *Armor) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Armor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Armor) GetArmorType() string {
	if x != nil {
		return x.ArmorType
	}
	return ""
}

func (x *Armor) GetDefense() uint64 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *Armor) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Armor) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Armor) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *Armor) GetSpecialEffect() string {
	if x != nil {
		return x.SpecialEffect
	}
	return ""
}

func (x *Armor) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetWeaponByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeaponByNameRequest) Reset() {
	*x = GetWeaponByNameRequest{}
	mi := &file_proto_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeaponByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeaponByNameRequest) ProtoMessage() {}

func (x *GetWeaponByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeaponByNameRequest.ProtoReflect.Descriptor instead.
func (*GetWeaponByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{2}
}

func (x *GetWeaponByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetWeaponByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weapon        *Weapon                `protobuf:"bytes,1,opt,name=weapon,proto3" json:"weapon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeaponByNameResponse) Reset() {
	*x = GetWeaponByNameResponse{}
	mi := &file_proto_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeaponByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeaponByNameResponse) ProtoMessage() {}

func (x *GetWeaponByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeaponByNameResponse.ProtoReflect.Descriptor instead.
func (*GetWeaponByNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{3}
}

func (x *GetWeaponByNameResponse) GetWeapon() *Weapon {
	if x != nil {
		return x.Weapon
	}
	return nil
}

type GetArmorByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArmorByNameRequest) Reset() {
	*x = GetArmorByNameRequest{}
	mi := &file_proto_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArmorByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArmorByNameRequest) ProtoMessage() {}

func (x *GetArmorByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArmorByNameRequest.ProtoReflect.Descriptor instead.
func (*GetArmorByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{4}
}

func (x *GetArmorByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetArmorByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Armor         *Armor                 `protobuf:"bytes,1,opt,name=armor,proto3" json:"armor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArmorByNameResponse) Reset() {
	*x = GetArmorByNameResponse{}
	mi := &file_proto_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArmorByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArmorByNameResponse) ProtoMessage() {}

func (x *GetArmorByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArmorByNameResponse.ProtoReflect.Descriptor instead.
func (*GetArmorByNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{5}
}

func (x *GetArmorByNameResponse) GetArmor() *Armor {
	if x != nil {
		return x.Armor
	}
	return nil
}

var File_proto_market_proto protoreflect.FileDescriptor

const file_proto_market_proto_rawDesc = "" +
	"\n" +
	"\x12proto/market.proto\x12\tinventory\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x02\n" +
	"\x06Weapon\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vweapon_type\x18\x03 \x01(\tR\n" +
	"weaponType\x12\x1d\n" +
	"\n" +
	"damage_min\x18\x04 \x01(\x04R\tdamageMin\x12\x1d\n" +
	"\n" +
	"damage_max\x18\x05 \x01(\x04R\tdamageMax\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x01R\x06weight\x12\x14\n" +
	"\x05price\x18\a \x01(\x04R\x05price\x12\x16\n" +
	"\x06rarity\x18\b \x01(\tR\x06rarity\x12%\n" +
	"\x0especial_effect\x18\t \x01(\tR\rspecialEffect\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8c\x02\n" +
	"\x05Armor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"armor_type\x18\x03 \x01(\tR\tarmorType\x12\x18\n" +
	"\adefense\x18\x04 \x01(\x04R\adefense\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x01R\x06weight\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x04R\x05price\x12\x16\n" +
	"\x06rarity\x18\a \x01(\tR\x06rarity\x12%\n" +
	"\x0especial_effect\x18\b \x01(\tR\rspecialEffect\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\",\n" +
	"\x16GetWeaponByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"D\n" +
	"\x17GetWeaponByNameResponse\x12)\n" +
	"\x06weapon\x18\x01 \x01(\v2\x11.inventory.WeaponR\x06weapon\"+\n" +
	"\x15GetArmorByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"@\n" +
	"\x16GetArmorByNameResponse\x12&\n" +
	"\x05armor\x18\x01 \x01(\v2\x10.inventory.ArmorR\x05armor2\xc0\x01\n" +
	"\rMarketService\x12X\n" +
	"\x0fGetWeaponByName\x12!.inventory.GetWeaponByNameRequest\x1a\".inventory.GetWeaponByNameResponse\x12U\n" +
	"\x0eGetArmorByName\x12 .inventory.GetArmorByNameRequest\x1a!.inventory.GetArmorByNameResponseB\x0eZ\fmarket/protob\x06proto3"

var (
	file_proto_market_proto_rawDescOnce sync.Once
	file_proto_market_proto_rawDescData []byte
)

func file_proto_market_proto_rawDescGZIP() []byte {
	file_proto_market_proto_rawDescOnce.Do(func() {
		file_proto_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_market_proto_rawDesc), len(file_proto_market_proto_rawDesc)))
	})
	return file_proto_market_proto_rawDescData
}

var file_proto_market_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_market_proto_goTypes = []any{
	(*Weapon)(nil),                  // 0: inventory.Weapon
	(*Armor)(nil),                   // 1: inventory.Armor
	(*GetWeaponByNameRequest)(nil),  // 2: inventory.GetWeaponByNameRequest
	(*GetWeaponByNameResponse)(nil), // 3: inventory.GetWeaponByNameResponse
	(*GetArmorByNameRequest)(nil),   // 4: inventory.GetArmorByNameRequest
	(*GetArmorByNameResponse)(nil),  // 5: inventory.GetArmorByNameResponse
	(*timestamppb.Timestamp)(nil),   // 6: google.protobuf.Timestamp
}
var file_proto_market_proto_depIdxs = []int32{
	6, // 0: inventory.Weapon.created_at:type_name -> google.protobuf.Timestamp
	6, // 1: inventory.Armor.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: inventory.GetWeaponByNameResponse.weapon:type_name -> inventory.Weapon
	1, // 3: inventory.GetArmorByNameResponse.armor:type_name -> inventory.Armor
	2, // 4: inventory.MarketService.GetWeaponByName:input_type -> inventory.GetWeaponByNameRequest
	4, // 5: inventory.MarketService.GetArmorByName:input_type -> inventory.GetArmorByNameRequest
	3, // 6: inventory.MarketService.GetWeaponByName:output_type -> inventory.GetWeaponByNameResponse
	5, // 7: inventory.MarketService.GetArmorByName:output_type -> inventory.GetArmorByNameResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_market_proto_init() }
func file_proto_market_proto_init() {
	if File_proto_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_market_proto_rawDesc), len(file_proto_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_market_proto_goTypes,
		DependencyIndexes: file_proto_market_proto_depIdxs,
		MessageInfos:      file_proto_market_proto_msgTypes,
	}.Build()
	File_proto_market_proto = out.File
	file_proto_market_proto_goTypes = nil
	file_proto_market_proto_depIdxs = nil
}
